leopardd_url_shortener_redirect:
    path: /{code}
    defaults: { _controller: LeoparddUrlShortenerBundle:Redirect:index }
    methods: GET
    requirements:
        code: \S+

leopardd_url_shortener_encode:
    path: /
    defaults: { _controller: LeoparddUrlShortenerBundle:Encode:index }
    methods: POST