leopardd_url_shortener_redirect:
    path: /{code}
    controller: Leopardd\Bundle\UrlShortenerBundle\Controller\RedirectController::indexAction
    methods: GET
    requirements:
        code: \S+

leopardd_url_shortener_encode:
    path: /
    controller: Leopardd\Bundle\UrlShortenerBundle\Controller\EncodeController::indexAction
    methods: POST